routes/web.php
		    	Route::any('notification','AdminController@notification')->name('admin.notification');
				
				// Customers
				Route::get('customers/table_data','CustomersController@table_data')->name('customers.data');
				Route::post('customers/changeStatus','CustomersController@changeStatus');
				Route::get('customers/checkEmail','CustomersController@checkEmail');
				Route::get('customers/getcustomerDetailByEmail','CustomersController@getcustomerDetailByEmail');
		    	Route::get('customers/getemailcustomers','CustomersController@getemailcustomers');
		    	Route::get('customers/customer-profile/{customerID}','CustomersController@customerProfile')->name('admin.customerProfile');
				Route::resource('customers','CustomersController');
				Route::post('/customers/delete','CustomersController@delete');
				// Customers

				// FAQ
				Route::post('faq/changestatus','FaqController@changeStatus')->name('faq.changestatus');
				Route::get('faq/table_data','FaqController@table_data')->name('faq.data');
				Route::resource('faq','FaqController');
				// FAQ

				// Factories
				Route::get('factories/table_data','FactoryController@table_data')->name('factories.data');
				Route::post('factories/changeStatus','FactoryController@changeStatus');
				Route::post('factories/getEditRecord','FactoryController@getEditRecord');
				Route::post('factories/editFactory/{factoryID}','FactoryController@update');
				Route::resource('factories','FactoryController');
				// factories

				// Charities
				Route::get('charities/table_data','CharityController@table_data')->name('charities.data');
				// Route::post('charities/getEditRecord','CharityController@getEditRecord');
				Route::post('charities/changeStatus','CharityController@changeStatus');
				Route::resource('charities','CharityController');
				// Charities

				// Terms
				Route::post('ContentManagement/store','ContentManagementController@storeterms');
				Route::get('terms','ContentManagementController@index')->name('admin.terms');
				Route::get('ContentManagement/edit_terms_data','ContentManagementController@editTerms'); 
				// Terms

				// Privacy Policy
				Route::post('ContentManagement/privateUpdate','ContentManagementController@storePrivatePolicy');
				Route::get('privacy-policy','ContentManagementController@privateIndex')->name('admin.privacy_policy');
				Route::get('ContentManagement/edit_private_data','ContentManagementController@editPrivate');
				// Privacy Policy

				// About Us
				Route::post('ContentManagement/aboutUpdate','ContentManagementController@storeAbout');
				Route::get('about-us','ContentManagementController@aboutIndex')->name('admin.about_us');
				Route::get('ContentManagement/edit_about_data','ContentManagementController@editAbout');
				// About Us

				// donationVsBid
				Route::post('ContentManagement/donation_vs_bid_update','ContentManagementController@storedonationVsBid');
				Route::get('donationVsBid','ContentManagementController@donationVsBidIndex')->name('admin.donationVsBid');
				Route::get('ContentManagement/edit_donation_vs_Bid','ContentManagementController@editdonationVsBid');
				// donationVsBid

				
				//Salesmans
				Route::get('salesmans/table_data','SalesmanController@table_data')->name('salesmans.data');
				Route::post('salesmans/changeStatus','SalesmanController@changeStatus');
				Route::resource('salesmans','SalesmanController');
				//Salesmans

				
				//Cutter
				Route::get('cutters/table_data','CutterController@table_data')->name('cutters.data');
				Route::post('cutters/changeStatus','CutterController@changeStatus');
				Route::resource('cutters','CutterController');
				//Cutter

				
				//QA
				Route::get('quality/table_data','QualityController@table_data')->name('quality.data');
				Route::post('quality/changeStatus','QualityController@changeStatus');
				Route::resource('quality','QualityController');
				//QA
				
				//otherUsers
				Route::get('otherUsers/table_data','OtherUsersController@table_data')->name('otherUsers.data');
				Route::post('otherUsers/changeStatus','OtherUsersController@changeStatus');
				Route::resource('otherUsers','OtherUsersController');
				//otherUsers

			

				//Website Content
				Route::post('webpage/website_content_update','WebsiteContentController@storeWebsiteContent');
				Route::get('webpage','WebsiteContentController@index');

				//Website Content

				// Promo Code
				Route::get('promoCodes/table_data','PromoCodeController@table_data')->name('promoCodes.data');
				Route::post('promoCodes/changeStatus','PromoCodeController@changeStatus')->name('promoCodes.changestatus');
				Route::resource('promoCodes','PromoCodeController');
				// Promo Code

				// Referral Code
				Route::get('referralCodes/table_data','ReferralCodeController@table_data')->name('referralCodes.data');
				Route::post('referralCodes/changeStatus','ReferralCodeController@changeStatus')->name('referralCodes.changestatus');
				Route::resource('referralCodes','ReferralCodeController');
				// Referral Code

				// FAQ Category
				Route::get('faqcategories/table_data','FaqCategoryController@table_data')->name('faqcategories.data');
				Route::post('faqcategories/getEditRecord','FaqCategoryController@getEditRecord');
				Route::post('faqcategories/editFaqCategory/{faqcategoryID}','FaqCategoryController@update');
				Route::resource('faqcategories','FaqCategoryController');
				// FAQ Category



				// Tailor
				Route::post('tailor/changeStatus','TailorController@changeStatus')->name('tailor.changestatus');
				Route::get('tailor/table_data','TailorController@table_data')->name('tailor.data');
				Route::resource('tailor','TailorController');
				Route::get('tailor/tailor-profile/{tailorID}','TailorController@tailorProfile')->name('admin.tailorProfile');
				// Tailor


				// Branches
				Route::get('branches/table_data','BranchController@table_data')->name('branches.data');
				Route::post('branches/changeStatus','BranchController@changeStatus');
				Route::get('branches/checkEmail','BranchController@checkEmail');
				Route::get('branches/getbranchDetailByEmail','BranchController@getbranchDetailByEmail');
		    	Route::get('branches/getemailbranches','BranchController@getemailbranches');
		    	Route::get('branches/branch-profile/{branchID}','BranchController@branchProfile')->name('admin.branchProfile');
				Route::resource('branches','BranchController');
				Route::post('/branches/delete','BranchController@delete');
				// Branches

				//suppliers
				Route::get('suppliers/table_data','SupplierController@table_data')->name('suppliers.data');
				Route::post('suppliers/changeStatus','SupplierController@changeStatus');
				Route::resource('suppliers','SupplierController');
				//suppliers

				//Catalogues
				Route::get('inventories','CataloguesController@inventories');
				Route::get('catalogues/home/{id}','CataloguesController@home')->name('catalogues.home');
				Route::get('catalogues/table_data','CataloguesController@table_data')->name('catalogues.data');
				Route::get('catalogues/product-details/{orderId}','CataloguesController@productDetails')->name('catalogues.productDetails');
				Route::post('catalogues/changeStatus','CataloguesController@changeStatus');
				Route::resource('catalogues', 'CataloguesController', ['except' => ['index']]);

				// Route::resource('income','IncomeController');
				Route::get('b2bincome/table_data','IncomebusinessController@table_data')->name('b2bincome.data');
				Route::resource('b2bincome','IncomebusinessController');
				Route::get('branchesincome','IncomeController@branchesincome');
				Route::get('income/main/{id}','IncomeController@main')->name('income.main');
				Route::get('income/home/{id}','IncomeController@home')->name('income.home');
				Route::get('income/table_data','IncomeController@table_data')->name('income.data');
				Route::resource('income', 'IncomeController', ['except' => ['index']]);

				//inventory
				Route::get('inventory/table_data','InventoryController@table_data')->name('inventory.data');
				Route::post('inventory/changeStatus','InventoryController@changeStatus');
				Route::resource('inventory','InventoryController');

				//Payments & Orders
				Route::get('payorders/table_data','PayordersController@table_data')->name('payorders.data');
				Route::get('createOrder','PayordersController@createOrder');
				Route::get('/createNextOrder', 'PayordersController@createNextOrder')->name('admin.createNextOrder');
				// Route::post("/createNextOrder", "PayordersController@createNextOrder")->name('admin.createNextOrder');
				// Route::post('createNextOrder','PayordersController@createNextOrder');
				Route::resource('payorders','PayordersController');
				Route::get('payorders/details/{payId}','PayordersController@details')->name('admin.payOrderDetails');
				Route::get('payorders/settle/{payId}','PayordersController@settle')->name('admin.payOrderSettle');
				Route::post('payorders/settled','PayordersController@settled');
				Route::get('purchaseorder','PayordersController@addorders')->name('admin.purchaseorder');//->name('admin.payOrderSettled');
				//Payments & Orders

				//payroll
				Route::get('payroll/table_data','PayrollController@table_data')->name('payroll.data');
				Route::post('payroll/changeStatus','PayrollController@changeStatus');
				Route::resource('payroll','PayrollController');
				Route::get('ajax/empData','PayrollController@ajaxEmpData');
				Route::get('payroll/generate/{id}','PayrollController@generate')->name('payroll.generate');
				Route::get('payroll/download/{id}','PayrollController@downloadPaySlip')->name('payroll.download');
				//payroll

				//salary
				Route::get('salary/table_data','SalaryController@table_data')->name('salary.data');
				Route::post('salary/changeStatus','SalaryController@changeStatus');
				Route::resource('salary','SalaryController');
				//salary

				//Payments
				Route::resource('payments','PaymentController');
				//Payments

				//Reports

app/Http/Controllers/Api/TeamApi/cutterController.php
<?php

namespace App\Http\Controllers\Api\TeamApi;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use App\Customer;
use App\Models\Order;
use App\Models\Product;
use App\Models\Salesman;

class cutterController extends Controller
{
	public function getCutters(){
		$cutterss = Salesman::where('type','4')->where('status','1')->get();
		if($cutterss->count() >0)
		{
			$cutterArray = [];
            foreach($cutterss as $cutter){
            	$val['id'] = $cutter['id'];
                $val['cutter_image'] = url('public/uploads/cutter').'/'.$cutter['image_name'];
                $val['cutter_name'] = $cutter['title'];
                $val['cutter_email'] = $cutter['email'];
                $val['description'] = $cutter['description'];
                $val['status'] = $cutter['status'];
                $val['phone'] = $cutter['phone'];
                $val['branch'] = $cutter['branch'];
                $val['monthly_target'] = $cutter['monthly_target'];
                $cutterArray[] = $val;
            }
            return response()->json(['result'=>$cutterArray, 'status'=>200, 'message' => 'Cutters']);
		}
		else{
			return response()->json(['status'=>404, 'message' => 'Cutters not found..!']);
		}
	}
}

resources/views/admin/cutter/edit.blade.php
@extends('admin.layouts.app')
@section('title','Manage Cutter')
@section('content')
<form method="POST" id="changeModuleForm" enctype="multipart/form-data" action="{{ url('admin/cutters/'.$cutter->id) }}">
{{ csrf_field() }}
{{ method_field('PATCH') }}
<div class="page-heading">
    <div class="pageheding-inner">
        <h1 class="page-common-head"><span>Manage Cutter</span></h1>
            <div class="breadcrumb">
                <span><a href="{{ url('admin','dashboard') }}">Dashboard</a></span>
                <span>></span>
                <span><a href="{{ url('admin','cutter') }}">Manage Cutter</a></span>
                <span>></span>
                <span class="active">{{$heading}} Manage Cutter</span>
            </div>
            <div class="new-customer-btn cancel-button">
                <a class="btn btn-primary pull-right" href="{{ url('admin','cutters') }}"> <i class="fa fa-times" aria-hidden="true"></i>Cancel</a>
            </div>
            <button type="submit" class="btn btn-primary save_btn">
                 <i class="fa fa-floppy-o" aria-hidden="true"></i>{{ __('Save') }}
            </button>
    </div>
</div>
<input type="hidden" name="id" id="id"  value="{{$cutter->id}}">
<div class="handi-form p-l-res">
    <div class="col-xs-12 col-sm-6 col-md-6 ">
        <div class="row">
            <div class="form-group error">
                <label for="inputName" class="col-xs-12 control-label">Name <span>*</span></label>
                <div class="col-xs-12">
                    <input type="text"  class="form-control has-error" id="title" name = "title"  value="{{$cutter->title}}" />
                    <p class="allTypeError"></p> 
                    @if ($errors->has('title'))
                    <span class="invalid-feedback">
                        <strong id="email-server-err-exists">{{ $errors->first('title') }}</strong>
                    </span>
                    @endif
                </div>
            </div>
        </div>
    </div>
     <div class="col-xs-12 col-sm-6 col-md-6 ">
        <div class="row">
            <div class="form-group error">
                <label for="inputName" class="col-xs-12 control-label">Email</label>
                <div class="col-xs-12">
                <input type="text"  class="form-control has-error" id="email" name = "email"  value="{{$cutter->email}}" />
                    
                   
                </div>
            </div>
        </div>
    </div>
     <div class="col-xs-12 col-sm-6 col-md-6 ">
        <div class="row">
            <div class="form-group error">
                <label for="inputName" class="col-xs-12 control-label">Contact Number</label>
                <div class="col-xs-12">
                <input type="text"  class="form-control has-error" id="phone" name = "phone"  value="{{$cutter->phone}}" />
                    
                   
                </div>
            </div>
        </div>
    </div>
     <div class="col-xs-12 col-sm-6 col-md-6 ">
        <div class="row">
            <div class="form-group error">
                <label for="inputName" class="col-xs-12 control-label">Factory Manager</label>
                <div class="col-xs-12">
                <select class="form-control has-error" id="factory_manager" name = "factory_manager">
                    @foreach($factory_assign_manager as $managerKey => $manager)

                    <option value="{{$managerKey}}" {{ ( $managerKey == $cutter->factory_manager) ? 'selected' : '' }}>{{$manager}}</option>

                    @endforeach
                </select> 
                    
                </div>
            </div>
        </div>
    </div>
     <div class="col-xs-12 col-sm-6 col-md-6 ">
        <div class="row">
            <div class="form-group error">
                <label for="inputName" class="col-xs-12 control-label">Monthly Target</label>
                <div class="col-xs-12">
                <input type="text"  class="form-control has-error" id="monthly_target" name = "monthly_target"  value="{{$cutter->monthly_target}}" />
                   
                </div>
            </div>
        </div>
    </div>

    <div class="col-xs-12 col-sm-6 col-md-6 ">
        <div class="row">
            <div class="form-group error">
                <label for="inputName" class="col-xs-12 control-label">Status <span>*</span></label>
                <div class="col-xs-12">
                    <select class="form-control has-error" id="status" name = "status">
                        <?php
                            if($cutter->status==1) 
                            { 
                            echo "<option value='1' selected>Active</option>
                                    <option value='0'>Inactive</option>"; 
                            } 
                            else
                            {
                            echo "<option value='1' >Active</option>
                                   <option value='0' selected>Inactive</option>"; 
                            }
                        ?>                            
                    </select> 
                    <p class="allTypeError"></p>
                    @if ($errors->has('status'))
                    <span class="invalid-feedback">
                        <strong>{{ $errors->first('status') }}</strong>
                    </span>
                    @endif
                </div>
            </div>
        </div>
    </div>
   
   
    <div class="col-xs-12 col-sm-12 col-md-12 ">
        <div class="row">
            <div class="col-xs-12 col-sm-12 img_upload-div ">
                <div class="form-group error">
                <label  class="control-label" for="image_name">Image</label>
                <div class="input-cover-modal">
                    <div class="image_preview error-outer">
                     
                        <img id="show-image-preview" src="{{ (!empty($cutter->image_name) && file_exists(public_path('uploads/cutter/'.$cutter->image_name)))?asset('uploads/cutter/'.$cutter->image_name):asset('images/common/default-image.jpg') }}" alt="" />
                        <div class="choose_file">
                            <input title="" type='file' id="image_name" name="image_name" />
                            <p><i class="fa fa-upload" aria-hidden="true"></i></p>
                        </div>
                        <input type="hidden" name="image-exist" id="image-exist" val = "no">
                    </div>
                    <p class="allTypeError"></p> 
                    @if ($errors->has('image_name'))
                    <span class="invalid-feedback">
                        <strong id="email-server-err-exists">{{ $errors->first('image_name') }}</strong>
                    </span>
                    @endif
                </div>
                </div>
            </div>
        </div>
    </div>
</div>
</form>
<script type="text/javascript" src="{{ asset('js/backend/cutter.js') }}"></script>
@stop

resources/views/admin/cutter/index.blade.php
@extends('admin.layouts.app')
@section('title','Cutter')
@section('content')
<div class="page-heading">
    <div class="pageheding-inner">
        <h1 class="page-common-head"><span>Cutter</span></h1>
        <div class="breadcrumb">
            <span><a href="{{ url('admin','dashboard') }}">Dashboard</a></span>
            <span>></span>
            <span class="active">Cutter</span>
        </div>
        <div class="new-customer-btn single-btn">
            <a class="btn btn-primary pull-right" id="show-add-form" href="{{ route('cutters.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> Add cutter</a>
        </div>
    </div>
</div>
<div class="mng-customer-table">
    <table class="table table-bordered" id="data-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Image</th>
                <th>Name</th>
                <th>Email</th>
                <th>Contact No.</th>
                <th>Factory Manager</th>
                <th>Monthly Target</th>
                <!-- <th>Type</th> -->
                <th>Rating</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
    </table>
</div>
<input id="data-table-url" type="hidden" value="{!! route('cutters.data') !!}">

<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="confirm-modal">
    <div class="modal-dialog modal-md modal-delete">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">DELETE</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this cutter?</p>
            </div>
            <div class="clearfix"></div>
            <div class="modal-footer text-center">
                <button type="button" class="btn btn-danger" data-dismiss="modal"> No</button>
                <button type="button" class="btn btn-primary primary deleteRecord" data-dismiss="modal" onclick="deleteRecord();">Yes</button>
                <input type="hidden" id="confirm-modal-delete-id" value="">
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="{{ asset('js/backend/cutter.js') }}"></script>

@if(session()->has('success'))
<script type="text/javascript">
    $.growl.notice({
        title: "Success!",
        message: 'success'
    });
</script>
@endif
@if(session()->has('error'))
<script type="text/javascript">
    $.growl.error({
        title: "Oops!",
        message: 'error'
    });
</script>
@endif
@stop