routes/web.php
		    	Route::get('branches/branch-profile/{branchID}','BranchController@branchProfile')->name('admin.branchProfile');
				Route::resource('branches','BranchController');
				Route::post('/branches/delete','BranchController@delete');
				// Branches

				//suppliers
				Route::get('suppliers/table_data','SupplierController@table_data')->name('suppliers.data');
				Route::post('suppliers/changeStatus','SupplierController@changeStatus');
				Route::resource('suppliers','SupplierController');
				//suppliers

				//Catalogues
				Route::get('inventories','CataloguesController@inventories');
				Route::get('catalogues/home/{id}','CataloguesController@home')->name('catalogues.home');
				Route::get('catalogues/table_data','CataloguesController@table_data')->name('catalogues.data');
				Route::get('catalogues/product-details/{orderId}','CataloguesController@productDetails')->name('catalogues.productDetails');
				Route::post('catalogues/changeStatus','CataloguesController@changeStatus');
				Route::resource('catalogues', 'CataloguesController', ['except' => ['index']]);

				// Route::resource('income','IncomeController');
				Route::get('b2bincome/table_data','IncomebusinessController@table_data')->name('b2bincome.data');
				Route::resource('b2bincome','IncomebusinessController');
				Route::get('branchesincome','IncomeController@branchesincome');
				Route::get('income/main/{id}','IncomeController@main')->name('income.main');
				Route::get('income/home/{id}','IncomeController@home')->name('income.home');
				Route::get('income/table_data','IncomeController@table_data')->name('income.data');
				Route::resource('income', 'IncomeController', ['except' => ['index']]);

				//inventory
				Route::get('inventory/table_data','InventoryController@table_data')->name('inventory.data');
				Route::post('inventory/changeStatus','InventoryController@changeStatus');
				Route::resource('inventory','InventoryController');

				//Payments & Orders
				Route::get('payorders/table_data','PayordersController@table_data')->name('payorders.data');
				Route::get('createOrder','PayordersController@createOrder');
				Route::get('/createNextOrder', 'PayordersController@createNextOrder')->name('admin.createNextOrder');
				// Route::post("/createNextOrder", "PayordersController@createNextOrder")->name('admin.createNextOrder');
				// Route::post('createNextOrder','PayordersController@createNextOrder');
				Route::resource('payorders','PayordersController');
				Route::get('payorders/details/{payId}','PayordersController@details')->name('admin.payOrderDetails');
				Route::get('payorders/settle/{payId}','PayordersController@settle')->name('admin.payOrderSettle');
				Route::post('payorders/settled','PayordersController@settled');
				Route::get('purchaseorder','PayordersController@addorders')->name('admin.purchaseorder');//->name('admin.payOrderSettled');
				//Payments & Orders

				//payroll
				Route::get('payroll/table_data','PayrollController@table_data')->name('payroll.data');
				Route::post('payroll/changeStatus','PayrollController@changeStatus');
				Route::resource('payroll','PayrollController');
				Route::get('ajax/empData','PayrollController@ajaxEmpData');
				Route::get('payroll/generate/{id}','PayrollController@generate')->name('payroll.generate');
				Route::get('payroll/download/{id}','PayrollController@downloadPaySlip')->name('payroll.download');
				//payroll

				//salary
				Route::get('salary/table_data','SalaryController@table_data')->name('salary.data');
				Route::post('salary/changeStatus','SalaryController@changeStatus');
				Route::resource('salary','SalaryController');
				//salary

				//Payments
				Route::resource('payments','PaymentController');
				//Payments

				//Reports
				Route::resource('reports','ReportController');
				//Reports

				// loyalty_programs
				Route::get('loyalty/table_data','LoyaltyController@table_data')->name('loyalty.data');
				Route::post('loyalty/changeStatus','LoyaltyController@changeStatus')->name('loyalty.changestatus');
				Route::resource('loyalty','LoyaltyController');
				// loyalty_programs

				// query
				Route::get('query/table_data','QueryController@table_data')->name('query.data');
				Route::post('query/changeStatus','QueryController@changeStatus')->name('query.changestatus');
				Route::resource('query','QueryController');
				// query
				
				//Orders
				Route::get('orders/table_data','OrdersController@table_data')->name('orders.data');
				Route::resource('orders','OrdersController');
				Route::get('orders/order-details/{orderId}','OrdersController@details')->name('admin.orderDetails');
				Route::post('add/comment', 'OrdersController@addComment');
				
				Route::get('finished/table_data','OrdersFinishedController@table_data')->name('finished.data');
				Route::resource('finished', 'OrdersFinishedController');
				//Orders

				//Accounts
				Route::get('accounts/table_data','AccountsController@table_data')->name('accounts.data');
				Route::get('accounts/summary','AccountsController@summary');
				Route::resource('accounts','AccountsController');
				//Accounts

				//Model Pricing
				Route::get('modelpricing/table_data','ModelPricingController@table_data')->name('modelpricing.data');
				Route::resource('modelpricing','ModelPricingController');
				//Model Pricing

				// Measurements
				Route::get('measurement/table_data','MeasurementController@table_data')->name('measurement.data');
				Route::resource('measurement','MeasurementController');
				// Measurements

				// Measurements
				Route::get('business/table_data','BusinessController@table_data')->name('business.data');
				Route::resource('business','BusinessController');
				Route::post('business/changeStatus','BusinessController@changeStatus');
				Route::get('business/order-details/{orderId}','BusinessController@details')->name('business.orderDetails');
				Route::get('business/order-pay/{orderId}','BusinessController@pay')->name('business.orderPay');
				// Measurements

				//uniform
				Route::get('uniform/table_data','UniformController@table_data')->name('uniform.data');
				Route::get('uniform/order-details/{orderId}','UniformController@details')->name('uniform.orderDetails');
				Route::resource('uniform','UniformController');
				Route::post('uniform/changeStatus','UniformController@changeStatus');
				Route::get('uniform/order-pay/{orderId}','UniformController@pay')->name('uniform.orderPay');
				//uniform
				
				//delay
				Route::get('delay/table_data','DelayController@table_data')->name('delay.data');
				Route::get('delay/order-details/{orderId}','DelayController@orderDetails')->name('delay.orderDetails');
				Route::resource('delay','DelayController');


				Route::get('Created','CreatedController@index');

				Route::get('b2b/table_data','B2BController@table_data')->name('b2b.data');
				Route::resource('b2b','B2BController');
				
				Route::resource('infactory','InfactoryController');

				Route::resource('defectiveorder','DefectiveOrderController');

				Route::resource('cutter','CuttingController');

				Route::resource('realized','RealizedController');

				//delay

				//subdashboard
				Route::get('pending/table_data','PendingController@table_data')->name('pending.data');
				Route::resource('pending','PendingController');
				Route::get('sewing/table_data','SewingController@table_data')->name('sewing.data');
				Route::resource('sewing','SewingController');

				Route::get('complete/table_data','CompletedController@table_data')->name('complete.data');
				Route::resource('complete','CompletedController');

				Route::get('delivery/table_data','DeliveredController@table_data')->name('delivery.data');
				Route::resource('delivery','DeliveredController');

				Route::get('defective/table_data','DefectiveController@table_data')->name('defective.data');
				Route::resource('defective','DefectiveController');

				Route::get('sewingorder/table_data','SewingOrderController@table_data')->name('sewingorder.data');
				Route::resource('sewingorder','SewingOrderController');

				Route::get('measurement/table_data','MeasurementOrderController@table_data')->name('measurement.data');
				Route::resource('measurement','MeasurementOrderController');

				Route::get('cutting/table_data','CuttingOrderController@table_data')->name('cutting.data');
				Route::resource('cutting','CuttingOrderController');

                Route::get('pendingorder/table_data','PendingOrderController@table_data')->name('pendingorder.data');
				Route::resource('pendingorder','PendingOrderController');

				Route::get('Bam01/table_data','Bam01Controller@table_data')->name('Bam01.data');
				Route::resource('Bam01','Bam01Controller');

				Route::get('Bam02/table_data','Bam02Controller@table_data')->name('Bam02.data');
				Route::resource('Bam02','Bam02Controller');

                Route::get('Bam03/table_data','Bam03Controller@table_data')->name('Bam03.data');
				Route::resource('Bam03','Bam03Controller');

				 Route::get('createBam01/table_data','CreateBAm01Controller@table_data')->name('createBam01.data');
				Route::resource('createBam01','CreateBAm01Controller');

				Route::get('createBam02/table_data','CreateBAm02Controller@table_data')->name('createBam02.data');
				Route::resource('createBam02','CreateBAm02Controller');

				Route::get('CreateBam03/table_data','CreateBAm03Controller@table_data')->name('CreateBam03.data');
				Route::resource('CreateBam03','CreateBAm03Controller');
                //subdashboard
                
				//Time Duration & Delivery Charges
				Route::get('buffer_day_delivery/table_data','BufferDayDeliveryChargeController@table_data')->name('buffer_day_delivery.data');
				Route::resource('buffer_day_delivery','BufferDayDeliveryChargeController');
				//Time Duration & Delivery Charges
			});

		});
	});
	Route::get('login', 'Auth\Admin\LoginController@login')->name('admin.auth.login');

app/Http/Controllers/Admin/BufferDayDeliveryChargeController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use File;
Use DB;
use Route;
use Illuminate\Support\Facades\Validator;
use App\Models\tax;

class BufferDayDeliveryChargeController extends AdminController
{
    
    public function __construct()
    {
        $model = new tax();
        $this->tableName =  $model->table;
        $this->ModuleName = 'taxes';
    }

    public function index()
    {
        return view('admin.BufferDayDeliveryCharge.index');  
    }

    public function table_data(Request $request)
    {
        $timeduration_delivery = tax::select('*');
        $datatables = Datatables::of($timeduration_delivery)
        // ->editColumn('created_at',function($timeduration_delivery)
        // {
        //     $html = formatDate($timeduration_delivery->created_at);
        //     return $html;
        // })
        // ->editColumn('updated_at',function($timeduration_delivery)
        // {
        //     $html = formatDate($timeduration_delivery->updated_at);
        //     return $html;
        // })
        ->addColumn('action',function ($timeduration_delivery){
            $html='<a class="btn btn-primary" value="'.$timeduration_delivery->id.'" href="'.route('buffer_day_delivery.edit',$timeduration_delivery->id).'"><i class="fa fa-pencil" aria-hidden="true"></i></a>'/*.'<button class="btn btn-danger btn-delete delete-records" title="Delete" value="'.$timeduration_delivery->id.'"><i class="fa fa-trash" aria-hidden="true"></i></button>'*/;
            return $html;
        })
        ->rawColumns(['buffer_days','delivery_charges','created_at','action']);
        return $datatables->make(true);
    }
   
    /**
     * Create Model
     */
    public function create()
    {
        $app = app();
        $bufferDelivery = $app->make('stdClass');
        $bufferDelivery->id = -1;
        $bufferDelivery->buffer_days = '';
        $bufferDelivery->delivery_charges = '';
        $bufferDelivery->tax_rate = '';

        return view('admin.BufferDayDeliveryCharge.edit')->with('heading','Create')->with('bufferDelivery',$bufferDelivery);
    }
    /**
     Edit Record
     */
    public function edit($bufferDelivery_id) {
        if(!empty($bufferDelivery_id) && is_numeric($bufferDelivery_id)) {
            $value = tax::find($bufferDelivery_id);
            $id = $value['id'];
            if( $id == $bufferDelivery_id ) {
               $bufferDelivery = DB::table($this->tableName)->select('*')->where('id',$bufferDelivery_id)->first();
             return view('admin.BufferDayDeliveryCharge.edit')->with('bufferDelivery',$bufferDelivery)->with('heading','Edit');
             //->with('userType',$userType);
            } else {
                return redirect()->route('buffer_day_delivery.index')->with('error',trans('message.invalidId'));
            }
        } else {
            return redirect()->route('buffer_day_delivery.index')->with('error',trans('message.invalidId'));
        }
    }
    /*
     * Update Record
     */
    public function update(Request $request,$bufferDelivery_id) {
        if($bufferDelivery_id>0)
            {
                request()->validate([
                    'buffer_days'         => 'required',
                    'delivery_charges'         => 'required',
                    'tax_rate'         => 'required'
                 ]);
                $data = array();
                $data['buffer_days'] = $request->get('buffer_days');
                $data['delivery_charges'] = $request->get('delivery_charges');
                $data['tax_rate'] = $request->get('tax_rate');

                    if(tax::where('id', $bufferDelivery_id)->update($data)) {
                        return redirect()->route('buffer_day_delivery.index')->with('success', $this->ModuleName.trans('message.UpdatedMsg'));
                    } else {
                        return redirect()->route('buffer_day_delivery.index')->with('error', $this->ModuleName.trans('message.networkErr'));
                    }
                }else { //for Create
                    $v = Validator::make($request->all(), [
                    'buffer_days'         => 'required',
                    'delivery_charges'         => 'required',
                    'tax_rate'         => 'required'
                  
                    ]);
                $data = array();
                $request = $request->input();

                tax::create($request);

                return redirect()->route('buffer_day_delivery.index')->with('Success', 'Created Successfully');      
            }
        }

    public function destroy(Request $request,$id){
        if($request->ajax()) {
            if($id && is_numeric($id)) {
                $destinationPath = public_path('/uploads/modelpricing');
                $deleteImg = tax::where('id', $id)->first()->image;
                if(tax::destroy($id)) {
                    if(isset($deleteImg) && !empty($deleteImg)) {
                        File::delete($destinationPath.'/'.$deleteImg);
                    }
                    echo json_encode(array('status' => 'success', 'message' => 'Deleted successfully'));exit;
                } else {
                    echo json_encode(array('status' => 'error', 'message' => 'Deleted successfully'));exit;
                }
            } else {
                echo json_encode(array('status' => 'error', 'message' => trans('message.networkErr')));exit;
            }
        }
     

    }
  
    /*
     * Show Record
     */
    public function show()
    {
        return redirect()->route('buffer_day_delivery.index')->with('error',trans('message.invalidId'));
    }


}

resources/views/admin/BufferDayDeliveryCharge/edit.blade.php
@extends('admin.layouts.app')
@section('title','Buffer & Delivery')
@section('content')
<form method="POST" id="changeModuleForm" enctype="multipart/form-data" action="{{ url('admin/buffer_day_delivery/'.$bufferDelivery->id) }}">
{{ csrf_field() }}
{{ method_field('PATCH') }}
<div class="page-heading">
    <div class="pageheding-inner">
        <h1 class="page-common-head"><span>Manage Buffer & Delivery</span></h1>
            <div class="breadcrumb">
                <span><a href="{{ url('admin','dashboard') }}">Dashboard</a></span>
                <span>></span>
                <span><a href="{{ url('admin','buffer_day_delivery') }}">Manage Buffer & Delivery</a></span>
                <span>></span>
                <span class="active">{{$heading}} Buffer & Delivery</span>
            </div>
            <div class="new-customer-btn cancel-button">
                <a class="btn btn-primary pull-right" href="{{ url('admin','buffer_day_delivery') }}"> <i class="fa fa-times" aria-hidden="true"></i>Cancel</a>
            </div>
            <button type="submit" class="btn btn-primary save_btn">
                 <i class="fa fa-floppy-o" aria-hidden="true"></i>{{ __('Save') }}
            </button>
    </div>
</div>
<input type="hidden" name="id" id="id"  value="{{$bufferDelivery->id}}">
<div class="handi-form p-l-res">
    <div class="col-xs-12 col-sm-6 col-md-4">
        <div class="row">
            <div class="form-group error">
                <label for="inputbuffer_days" class="col-xs-12 control-label">Buffer Days<span>*</span></label>
                <div class="col-xs-12">
                    <input type="text"  class="form-control has-errorbuffer_days" name = "buffer_days"  value="{{$bufferDelivery->buffer_days}}" required="required" />
                    <p class="allTypeError"></p> 
                    @if ($errors->has('buffer_days'))
                    <span class="invalid-feedback">
                        <strong id="email-server-err-exists">{{ $errors->first('buffer_days') }}</strong>
                    </span>
                    @endif
                </div>
            </div>
        </div>
    </div>
     <div class="col-xs-12 col-sm-6 col-md-4 ">
        <div class="row">
            <div class="form-group error">
                <label for="inputdelivery_charges" class="col-xs-12 control-label">Delivery Charges(In SAR)<span>*</span></label>
                <div class="col-xs-12">
                <input type="text"  class="form-control has-error" id="delivery_charges" name = "delivery_charges"  value="{{$bufferDelivery->delivery_charges}}" required="required"/>
                    
                   
                </div>
            </div>
        </div>
    </div>
     <div class="col-xs-12 col-sm-6 col-md-4 ">
        <div class="row">
            <div class="form-group error">
                <label for="inputtax_rate" class="col-xs-12 control-label">Tax Rate(In %)<span>*</span></label>
                <div class="col-xs-12">
                <input type="text"  class="form-control has-error" id="tax_rate" name = "tax_rate"  value="{{$bufferDelivery->tax_rate}}" required="required"/>
                    
                   
                </div>
            </div>
        </div>
    </div>

</div>
</form>
<script type="text/javascript" src="{{ asset('js/backend/bufferDayDelivery.js') }}"></script>
@stop

resources/views/admin/BufferDayDeliveryCharge/index.blade.php
@extends('admin.layouts.app')
@section('title','Buffer & Delivery')
@section('content')
<div class="page-heading">
    <div class="pageheding-inner">
        <h1 class="page-common-head"><span>Delivery Charges</span></h1>
        <div class="breadcrumb">
            <span><a href="{{ url('admin','dashboard') }}">Dashboard</a></span>
            <span>></span>
            <span class="active">Delivery Charges</span>
        </div>
        <!-- <div class="new-customer-btn single-btn">
            <a class="btn btn-primary pull-right" id="show-add-form" href="{{ route('buffer_day_delivery.create') }}"><i class="fa fa-plus" aria-hidden="true"></i>Add Charge</a>
        </div> -->
    </div>
</div>
<div class="mng-customer-table">
    <table class="table table-bordered" id="data-table">
        <thead>
            <tr>
                <th>Tax Rate (In %)</th>
                <th>Buffer Days</th>
                <th>Delivery Charges (In SAR)</th>
                <th>Updated On</th>
                <th><span class="act-block">Action</span></th>
            </tr>
        </thead>
    </table>
</div>
<div class="row">
    <div class="col-sm-12">
        <span><strong>Note:</strong></span>
        Completion date = Buffer Days + (Number of orders in queue/ ( 4 * number of active sewers))
    </div>
</div>
<input id="data-table-url" type="hidden" value="{!! route('buffer_day_delivery.data') !!}">
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="confirm-modal">
    <div class="modal-dialog modal-md modal-delete">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">DELETE</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this Model?</p>
            </div>
            <div class="clearfix"></div>
            <div class="modal-footer text-center">
                <button type="button" class="btn btn-danger" data-dismiss="modal"> No</button>
                <button type="button" class="btn btn-primary primary deleteRecord" data-dismiss="modal" onclick="deleteRecord();">Yes</button>
                <input type="hidden" id="confirm-modal-delete-id" value="">
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="{{ asset('js/backend/bufferDayDelivery.js') }}"></script>

@if(session()->has('success'))
<script type="text/javascript">
    $.growl.notice({
        title: "Success!",
        message: 'success'
    });
</script>
@endif
@if(session()->has('error'))
<script type="text/javascript">
    $.growl.error({
        title: "Oops!",
        message: 'error'
    });
</script>
@endif
@stop