routes/web.php
				Route::post('factories/editFactory/{factoryID}','FactoryController@update');
				Route::resource('factories','FactoryController');
				// factories

				// Charities
				Route::get('charities/table_data','CharityController@table_data')->name('charities.data');
				// Route::post('charities/getEditRecord','CharityController@getEditRecord');
				Route::post('charities/changeStatus','CharityController@changeStatus');
				Route::resource('charities','CharityController');
				// Charities

				// Terms
				Route::post('ContentManagement/store','ContentManagementController@storeterms');
				Route::get('terms','ContentManagementController@index')->name('admin.terms');
				Route::get('ContentManagement/edit_terms_data','ContentManagementController@editTerms'); 
				// Terms

				// Privacy Policy
				Route::post('ContentManagement/privateUpdate','ContentManagementController@storePrivatePolicy');
				Route::get('privacy-policy','ContentManagementController@privateIndex')->name('admin.privacy_policy');
				Route::get('ContentManagement/edit_private_data','ContentManagementController@editPrivate');
				// Privacy Policy

				// About Us
				Route::post('ContentManagement/aboutUpdate','ContentManagementController@storeAbout');
				Route::get('about-us','ContentManagementController@aboutIndex')->name('admin.about_us');
				Route::get('ContentManagement/edit_about_data','ContentManagementController@editAbout');
				// About Us

				// donationVsBid
				Route::post('ContentManagement/donation_vs_bid_update','ContentManagementController@storedonationVsBid');
				Route::get('donationVsBid','ContentManagementController@donationVsBidIndex')->name('admin.donationVsBid');
				Route::get('ContentManagement/edit_donation_vs_Bid','ContentManagementController@editdonationVsBid');
				// donationVsBid

				
				//Salesmans
				Route::get('salesmans/table_data','SalesmanController@table_data')->name('salesmans.data');
				Route::post('salesmans/changeStatus','SalesmanController@changeStatus');
				Route::resource('salesmans','SalesmanController');
				//Salesmans

				
				//Cutter
				Route::get('cutters/table_data','CutterController@table_data')->name('cutters.data');
				Route::post('cutters/changeStatus','CutterController@changeStatus');
				Route::resource('cutters','CutterController');
				//Cutter

				
				//QA
				Route::get('quality/table_data','QualityController@table_data')->name('quality.data');
				Route::post('quality/changeStatus','QualityController@changeStatus');
				Route::resource('quality','QualityController');
				//QA
				
				//otherUsers
				Route::get('otherUsers/table_data','OtherUsersController@table_data')->name('otherUsers.data');
				Route::post('otherUsers/changeStatus','OtherUsersController@changeStatus');
				Route::resource('otherUsers','OtherUsersController');
				//otherUsers

			

				//Website Content
				Route::post('webpage/website_content_update','WebsiteContentController@storeWebsiteContent');
				Route::get('webpage','WebsiteContentController@index');

				//Website Content

				// Promo Code
				Route::get('promoCodes/table_data','PromoCodeController@table_data')->name('promoCodes.data');
				Route::post('promoCodes/changeStatus','PromoCodeController@changeStatus')->name('promoCodes.changestatus');
				Route::resource('promoCodes','PromoCodeController');
				// Promo Code

				// Referral Code
				Route::get('referralCodes/table_data','ReferralCodeController@table_data')->name('referralCodes.data');
				Route::post('referralCodes/changeStatus','ReferralCodeController@changeStatus')->name('referralCodes.changestatus');
				Route::resource('referralCodes','ReferralCodeController');
				// Referral Code

				// FAQ Category
				Route::get('faqcategories/table_data','FaqCategoryController@table_data')->name('faqcategories.data');
				Route::post('faqcategories/getEditRecord','FaqCategoryController@getEditRecord');
				Route::post('faqcategories/editFaqCategory/{faqcategoryID}','FaqCategoryController@update');
				Route::resource('faqcategories','FaqCategoryController');
				// FAQ Category



				// Tailor
				Route::post('tailor/changeStatus','TailorController@changeStatus')->name('tailor.changestatus');
				Route::get('tailor/table_data','TailorController@table_data')->name('tailor.data');
				Route::resource('tailor','TailorController');
				Route::get('tailor/tailor-profile/{tailorID}','TailorController@tailorProfile')->name('admin.tailorProfile');
				// Tailor


				// Branches
				Route::get('branches/table_data','BranchController@table_data')->name('branches.data');
				Route::post('branches/changeStatus','BranchController@changeStatus');
				Route::get('branches/checkEmail','BranchController@checkEmail');
				Route::get('branches/getbranchDetailByEmail','BranchController@getbranchDetailByEmail');
		    	Route::get('branches/getemailbranches','BranchController@getemailbranches');
		    	Route::get('branches/branch-profile/{branchID}','BranchController@branchProfile')->name('admin.branchProfile');
				Route::resource('branches','BranchController');
				Route::post('/branches/delete','BranchController@delete');
				// Branches

				//suppliers
				Route::get('suppliers/table_data','SupplierController@table_data')->name('suppliers.data');
				Route::post('suppliers/changeStatus','SupplierController@changeStatus');
				Route::resource('suppliers','SupplierController');
				//suppliers

				//Catalogues
				Route::get('inventories','CataloguesController@inventories');
				Route::get('catalogues/home/{id}','CataloguesController@home')->name('catalogues.home');
				Route::get('catalogues/table_data','CataloguesController@table_data')->name('catalogues.data');
				Route::get('catalogues/product-details/{orderId}','CataloguesController@productDetails')->name('catalogues.productDetails');
				Route::post('catalogues/changeStatus','CataloguesController@changeStatus');
				Route::resource('catalogues', 'CataloguesController', ['except' => ['index']]);

				// Route::resource('income','IncomeController');
				Route::get('b2bincome/table_data','IncomebusinessController@table_data')->name('b2bincome.data');
				Route::resource('b2bincome','IncomebusinessController');
				Route::get('branchesincome','IncomeController@branchesincome');
				Route::get('income/main/{id}','IncomeController@main')->name('income.main');
				Route::get('income/home/{id}','IncomeController@home')->name('income.home');
				Route::get('income/table_data','IncomeController@table_data')->name('income.data');
				Route::resource('income', 'IncomeController', ['except' => ['index']]);

				//inventory
				Route::get('inventory/table_data','InventoryController@table_data')->name('inventory.data');
				Route::post('inventory/changeStatus','InventoryController@changeStatus');
				Route::resource('inventory','InventoryController');

				//Payments & Orders
				Route::get('payorders/table_data','PayordersController@table_data')->name('payorders.data');
				Route::get('createOrder','PayordersController@createOrder');
				Route::get('/createNextOrder', 'PayordersController@createNextOrder')->name('admin.createNextOrder');
				// Route::post("/createNextOrder", "PayordersController@createNextOrder")->name('admin.createNextOrder');
				// Route::post('createNextOrder','PayordersController@createNextOrder');
				Route::resource('payorders','PayordersController');
				Route::get('payorders/details/{payId}','PayordersController@details')->name('admin.payOrderDetails');
				Route::get('payorders/settle/{payId}','PayordersController@settle')->name('admin.payOrderSettle');
				Route::post('payorders/settled','PayordersController@settled');
				Route::get('purchaseorder','PayordersController@addorders')->name('admin.purchaseorder');//->name('admin.payOrderSettled');
				//Payments & Orders

				//payroll
				Route::get('payroll/table_data','PayrollController@table_data')->name('payroll.data');
				Route::post('payroll/changeStatus','PayrollController@changeStatus');
				Route::resource('payroll','PayrollController');
				Route::get('ajax/empData','PayrollController@ajaxEmpData');
				Route::get('payroll/generate/{id}','PayrollController@generate')->name('payroll.generate');
				Route::get('payroll/download/{id}','PayrollController@downloadPaySlip')->name('payroll.download');
				//payroll

				//salary
				Route::get('salary/table_data','SalaryController@table_data')->name('salary.data');
				Route::post('salary/changeStatus','SalaryController@changeStatus');
				Route::resource('salary','SalaryController');
				//salary

				//Payments
				Route::resource('payments','PaymentController');
				//Payments

				//Reports
				Route::resource('reports','ReportController');
				//Reports

				// loyalty_programs
				Route::get('loyalty/table_data','LoyaltyController@table_data')->name('loyalty.data');
				Route::post('loyalty/changeStatus','LoyaltyController@changeStatus')->name('loyalty.changestatus');
				Route::resource('loyalty','LoyaltyController');
				// loyalty_programs

				// query
				Route::get('query/table_data','QueryController@table_data')->name('query.data');
				Route::post('query/changeStatus','QueryController@changeStatus')->name('query.changestatus');
				Route::resource('query','QueryController');
				// query
				
				//Orders
				Route::get('orders/table_data','OrdersController@table_data')->name('orders.data');
				Route::resource('orders','OrdersController');
				Route::get('orders/order-details/{orderId}','OrdersController@details')->name('admin.orderDetails');
				Route::post('add/comment', 'OrdersController@addComment');
				
				Route::get('finished/table_data','OrdersFinishedController@table_data')->name('finished.data');
				Route::resource('finished', 'OrdersFinishedController');
				//Orders

				//Accounts
				Route::get('accounts/table_data','AccountsController@table_data')->name('accounts.data');
				Route::get('accounts/summary','AccountsController@summary');
				Route::resource('accounts','AccountsController');

app/Http/Controllers/Admin/ReferralCodeController.php
<?php

namespace App\Http\Controllers\Admin;

Use App\Models\ReferralCode;
Use DB;
Use Route;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use Illuminate\Support\Facades\Validator;
use File;
use Illuminate\Support\Facades\Input;

class ReferralCodeController extends AdminController
{
     public function __construct()
    {
        $model = new ReferralCode();
        $this->tableName =  $model->table;
        $this->ModuleName = 'ReferralCode';
    }

    public function index()
    {
       return view('admin.referralCodes.index');
    }



    public function table_data(Request $request){
        $referralcodes  = ReferralCode::select('*');
        $datatables = Datatables::of($referralcodes)
            
             ->editColumn('name',function ($referralCode){
               $html = $referralCode->name;
               return $html;
            })
             ->editColumn('email',function ($referralCode){
               $html = $referralCode->email;
               return $html;
            })
             ->editColumn('code',function ($referralCode){
               $html = $referralCode->code;
               return $html;
            })
             
           ->editColumn('status',function ($referralCode){
                $html = '<label class="switch" id="changeStatus" module-id="'.$referralCode->id.'">';
                if($referralCode->status){
                    $html .= '<input type="checkbox" checked="checked">';
                } else {
                    $html .= '<input type="checkbox">';
                }
                $html .= '<span class="lever round"></span></label>';
                return $html;
            })
            ->addColumn('action',function ($referralCode){
                $html='<a class="btn btn-primary" value="'.$referralCode->id.'" href="'.route('referralCodes.edit',$referralCode->id).'"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                        <button class="btn btn-danger btn-delete delete-records" value="'.$referralCode->id.'"><i class="fa fa-trash" aria-hidden="true"></i></button>';
                return $html;
            })
            ->editColumn('created_at',function($referralCode)
            {
                $html = formatDate($referralCode->created_at);
                return $html;
            })
         
            ->rawColumns(['name','email','code','status', 'action']);
            return $datatables->make(true);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request){

        $app = app();
        $referralCode = $app->make('stdClass');
        $referralCode->id = -1;
        $referralCode->name = '';
        $referralCode->email = '';
        $referralCode->code = 'GT'.random_number(8);
        $referralCode->status=1;
       
        return view('admin.referralCodes.edit')->with('heading','Create')->with('referralCode',$referralCode);
    }



     /*
     * Change Status
     */
    public function changeStatus(Request $request) {
        if($request->ajax()) {
            $id   = $request->get('id');
            if($id && is_numeric(($id))) {
                if(ReferralCode::where('id', $id)->update(array('status' => $request->get('status')))) {
                    echo json_encode(array('status' => 'success', 'message' => trans('message.statusUpdated')));exit;
                } else {
                    echo json_encode(array('status' => 'error', 'message' => trans('message.networkErr')));exit;
                }
            }
            echo json_encode(array('status' => 'error', 'message' => trans('message.networkErr')));exit;
        }
    }

    /*
     * Edit Record
     */
    public function edit($referralCode_id) {
        if(!empty($referralCode_id) && is_numeric($referralCode_id)) {
            $value = ReferralCode::find($referralCode_id);
            $id = $value['id'];
            if( $id == $referralCode_id ) {
               $referralCode = DB::table($this->tableName)->select('*')->where('id',$referralCode_id)->first();
             return view('admin.referralCodes.edit')->with('referralCode',$referralCode)->with('heading','Edit');
            } else {
                return redirect()->route('referralCodes.index')->with('error',trans('message.invalidId'));
            }
        } else {
            return redirect()->route('referralCodes.index')->with('error',trans('message.invalidId'));
        }
    }

    /*
     * Update Record
     */
    public function update(Request $request,$referralCode_id) {
        if($referralCode_id>0)
            {
                request()->validate([
                    'name'         => 'required',
                    'email'        => 'required',
                    'code' =>         'required|unique:referral_codes,code,'. $referralCode_id .''
                ]);
                $data['name']         = $request->get('name');
                $data['email']        = $request->get('email');
                $data['code']         = $request->get('code');
                $data['status']       = $request->get('status');
                    if(ReferralCode::where('id', $referralCode_id)->update($data)) {
                        return redirect()->route('referralCodes.index')->with('success', $this->ModuleName.trans('message.UpdatedMsg'));
                    } else {
                        return redirect()->route('referralCodes.index')->with('error', $this->ModuleName.trans('message.networkErr'));
                    }
                }else {
                $v = Validator::make($request->all(), [
                'name'         => 'required',
                'email'        => 'required',
                'code'         => 'required|unique:referral_codes,code'      
                ]);
                if ($v->fails()) {
            return back()->with('errors', $v->errors())->withInput();
        }else{

        
             $request = $request->input();
                ReferralCode::create($request);
                return redirect()->route('referralCodes.index')->with('success', $this->ModuleName.trans('message.UpdatedMsg')); 
                }     
            }
         }
        /*
        * Delete record
        */
        public function destroy($id) {
        ReferralCode::destroy($id);
        return response()->json(['status'=> 'success', 'message' => $this->ModuleName.trans('message.DeletedMsg')]);
        }   
  

        /*
         * Check code existing
         */

        // public function checkCode() {
        //     $userid = Input::get('userid');
        //     $code = Input::get('code');
        //     if($code != "") {
        //         if($userid == '') {
        //             $checkExist = ReferralCode::where('code', '=', $code)->first();

        //         } else {
        //             $checkExist = ReferralCode::where([['code', '=', $code], ['id', '!=', $userid]])->first();
                    
        //         }
        //         if ($checkExist === null) {
        //             echo "true";
        //         } else {
        //             echo "false";
        //         }
        //     }
        // }



}

resources/views/admin/referralCodes/edit.blade.php
@extends('admin.layouts.app')
@section('title','Promo Codes')
@section('content')
<form method="POST" id="changeModuleForm" enctype="multipart/form-data" action="{{ url('admin/referralCodes/'.$referralCode->id) }}">
{{ csrf_field() }}
{{ method_field('PATCH') }}
<div class="page-heading">
    <div class="pageheding-inner">
        <h1 class="page-common-head"><span>Promo Codes</span></h1>
            <div class="breadcrumb">
                <span><a href="{{ url('admin','dashboard') }}">Dashboard</a></span>
                <span>></span>
                <span><a href="{{ url('admin','referralCodes') }}">Referral Code</a></span>
                <span>></span>
                <span class="active">{{$heading}} Referral Code</span>
            </div>
            <div class="new-customer-btn cancel-button">
                <a class="btn btn-primary pull-right" href="{{ url('admin','referralCodes') }}"> <i class="fa fa-times" aria-hidden="true"></i>Cancel</a>
            </div>
            <button type="submit" class="btn btn-primary save_btn">
                 <i class="fa fa-floppy-o" aria-hidden="true"></i>{{ __('Save') }}
            </button>
    </div>
</div>
<input type="hidden" name="id" id="id"  value="{{$referralCode->id}}">
<div class="handi-form p-l-res">
    <div class="col-xs-12 col-sm-6 col-md-6 ">
        <div class="row">
            <div class="form-group error">
                <label for="inputName" class="col-xs-12 control-label">Name <span>*</span></label>
                <div class="col-xs-12">
                    <input type="text"  class="form-control has-error" id="name" name = "name"  value="{{$referralCode->name}}" />
                    <p class="allTypeError"></p> 
                    @if ($errors->has('name'))
                    <span class="invalid-feedback">
                        <strong id="email-server-err-exists">{{ $errors->first('name') }}</strong>
                    </span>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 ">
        <div class="row">
            <div class="form-group error">
                <label for="inputName" class="col-xs-12 control-label">Email <span>*</span></label>
                <div class="col-xs-12">
                    <input type="text"  class="form-control has-error" id="email" name = "email"  value="{{$referralCode->email}}" />
                    <p class="allTypeError"></p> 
                    @if ($errors->has('email'))
                    <span class="invalid-feedback">
                        <strong id="email-server-err-exists">{{ $errors->first('email') }}</strong>
                    </span>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 ">
        <div class="row">
            <div class="form-group error">
                <label for="inputName" class="col-xs-12 control-label">Code <span>*</span></label>
                <div class="col-xs-12">
                    <input type="text"  class="form-control has-error" id="code" name = "code"  value="{{$referralCode->code}}" />
                    <p class="allTypeError"></p> 
                    @if ($errors->has('code'))
                    <span class="invalid-feedback">
                        <strong id="email-server-err-exists">{{ $errors->first('code') }}</strong>
                    </span>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 ">
        <div class="row">
            <div class="form-group error">
                <label for="inputName" class="col-xs-12 control-label">Status <span>*</span></label>
                <div class="col-xs-12">
                    <select class="form-control has-error" id="status" name = "status">
                        <?php
                            if($referralCode->status==1) 
                            { 
                            echo "<option value='1' selected>Active</option>
                                    <option value='0'>Inactive</option>"; 
                            } 
                            else
                            {
                            echo "<option value='1' >Active</option>
                                   <option value='0' selected>Inactive</option>"; 
                            }
                        ?>                            
                    </select> 
                    <p class="allTypeError"></p>
                    @if ($errors->has('status'))
                    <span class="invalid-feedback">
                        <strong>{{ $errors->first('status') }}</strong>
                    </span>
                    @endif
                </div>
            </div>
        </div>
      <!--   <input type="hidden" name="referral_id" id="referral_id" value="{{$referralCode->id}}" /> -->
    </div>
    
  </div>
</form>
<script type="text/javascript" src="{{ asset('js/backend/referralCodes.js') }}"></script>
@stop

resources/views/admin/referralCodes/index.blade.php
@extends('admin.layouts.app')
@section('title','Promo Codes')
@section('content')
<div class="page-heading">
    <div class="pageheding-inner">
        <h1 class="page-common-head"><span>Promo Codes</span></h1>
        <div class="breadcrumb">
            <span><a href="{{ url('admin','dashboard') }}">Dashboard</a></span>
            <span>></span>
            <span class="active">Manage Promo Codes</span>
        </div>
        <div class="new-customer-btn single-btn">
            <a class="btn btn-primary pull-right" id="show-add-form" href="{{ route('referralCodes.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> Add Promo Code</a>
        </div>
    </div>
</div>
<div class="mng-customer-table">
    <table class="table table-bordered" id="data-table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Code</th>
                <th>Status</th>
                <th>Added On</th>
                <!-- <th>Updated On</th> -->
                <th>Action</th>
            </tr>
        </thead>
    </table>
</div>
<input id="data-table-url" type="hidden" value="{!! route('referralCodes.data') !!}">

<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="confirm-modal">
    <div class="modal-dialog modal-md modal-delete">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="myModalLabel">DELETE</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <p>There may be User(s) which are associated with this Promo Code.
                Are you sure you want to delete this Promo Code?</p>
            </div>
            <div class="clearfix"></div>
            <div class="modal-footer text-center">
                <button type="button" class="btn btn-danger" data-dismiss="modal"> No</button>
                <button type="button" class="btn btn-primary primary deleteRecord" data-dismiss="modal" onclick="deleteRecord();">Yes</button>
                <input type="hidden" id="confirm-modal-delete-id" value="">
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="{{ asset('js/backend/referralCodes.js') }}"></script>

@if(session()->has('success'))
    <script type="text/javascript">
        $.growl.notice({title: "Success!", message:  '{!! session('success') !!}' });
    </script>
@endif
@if(session()->has('error'))
    <script type="text/javascript">
        $.growl.error({title: "Oops!", message:  '{!! session('error') !!}' });
    </script>
@endif
@stop